Library-Management-System-main/LMS/LMS/urls.py
from django.urls import path, include
urlpatterns = [
    path('', include('library.urls'))
]

Library-Management-System-main/LMS/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_new_student', views.add_new_student, name='new_student'),
    path('add_new_book', views.add_new_book, name='new_book'),
    path('add_book_issue', views.add_book_issue, name='book_issue'),
    path('add_new_book_instance', views.add_new_book_instance, name='add_new_book_instance'),
    path('show_students', views.view_students, name='show_student_record'),
    path('view_books', views.view_books, name='show_book_record'),
    path('view_books_issued', views.view_bissue, name='show_issue_record'),
    path('edit/student/<str:roll>',views.edit_student_data,name="Edit Student data"),
    path('edit/book/<uuid:id>',views.edit_book_data,name="Edit Student data"),
    path('delete/student/<str:roll>',views.delete_student,name="Delete Student data"),
    path('delete/book/<str:id>',views.delete_book,name="Delete book data"),
    path('return_book/<int:id>',views.return_issued_book,name="return_issued_book"),
    path('edit_issued/<int:id>',views.edit_issued,name="edit_issued"),

]

Library-Management-System-main/LMS/library/models.py
from django.db import models
from datetime import datetime,timedelta
import uuid

class Students(models.Model):
    roll_number = models.CharField(max_length=100,unique=True)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    program = models.CharField(max_length=100)
    Guardian_name=models.CharField(max_length=100,help_text="parent/guardian full name")
    Email=models.EmailField(max_length=100,help_text="Guardian/parent e-mail")
    def __str__(self):
        return self.fullname

class Book(models.Model):
    book_title = models.CharField(max_length=200)
    book_author = models.CharField(max_length=100)
    book_pages = models.PositiveIntegerField()
    summary=models.TextField(max_length=500, help_text="Summary about the book",null=True,blank=True)
    def __str__(self):
        return self.book_title

class BookInstance(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,help_text="Book unique id across the Library")
    book=models.ForeignKey('Book', on_delete=models.CASCADE,null=True)
    book_number=models.PositiveIntegerField(null=True,help_text="Book number for books of the save kind")
    Is_borrowed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.id} {self.book}"

def get_returndate():
    return datetime.today() + timedelta(days=8)

class Book_Issue(models.Model):
    student = models.ForeignKey('Students', on_delete=models.CASCADE)
    book_instance = models.ForeignKey('BookInstance', on_delete=models.CASCADE)
    issue_date = models.DateTimeField(auto_now=True,help_text="Date the book is issued")
    due_date = models.DateTimeField(default=get_returndate(),help_text="Date the book is due to")
    date_returned=models.DateField(null=True, blank=True,help_text="Date the book is returned")
    remarks_on_issue = models.CharField(max_length=100, default="Book in good condition", help_text="Book remarks/condition during issue")
    remarks_on_return = models.CharField(max_length=100, default="Book in good condition", help_text="Book remarks/condition during return")

    def __str__(self):
        return self.student.fullname + " borrowed " + self.book.book_title

Library-Management-System-main/LMS/library/forms.py
from django import forms
from .models import Students, Book, Book_Issue,BookInstance

class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        
class Book_instanceForm(forms.ModelForm):
    class Meta:
        model=BookInstance
        fields = ['book','book_number']

class Book_IssueForm(forms.ModelForm):
    class Meta:
        model=Book_Issue
        exclude = ['issue_date', 'due_date','remarks_on_return','date_returned']

Library-Management-System-main/LMS/library/views.py
from django.shortcuts import render, redirect,HttpResponse
from .forms import StudentsForm, BookForm, Book_IssueForm,Book_instanceForm
from .models import Students, Book, Book_Issue,BookInstance


def index(request):
    return(render(request, 'index.html'))


def add_new_student(request):
    if request.method=="POST":
        form = StudentsForm((request.POST))
        if form.is_valid():
            form.save()
            return redirect('/show_students')
    else:
        form = StudentsForm
    return (render(request, 'add_new_student.html', {'form':form}))


def add_new_book(request):
    if request.method=="POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form=form.save()
            book_instance=BookInstance(book=form)
            book_instance.save()
            return redirect('/view_books')
    else:
        form = BookForm
        form_instance=Book_instanceForm
        return (render(request, 'add_new_book.html', {'form':form,"form_instance":form_instance}))

def add_new_book_instance(request):
    form=Book_instanceForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('/view_books')


def add_book_issue(request):
    if request.method=="POST":
        form = Book_IssueForm(request.POST)
        if form.is_valid():
            # save data
            unsaved_form=form.save(commit=False)
            book_to_save=BookInstance.objects.get(id=unsaved_form.book_instance.id)
            book_to_save.Is_borrowed=True
            book_to_save.save()
            form.save()
            form.save_m2m()
        return redirect('/view_books_issued')
    else:
        context={'form':Book_IssueForm,"book":BookInstance.objects.filter(Is_borrowed=False)}
        return render(request, 'add_book_issue.html',context=context)

def view_students(request):
    students = Students.objects.order_by('-id')
    return render(request,'view_students.html', {'students': students})

def view_books(request):
    books=BookInstance.objects.order_by('id')
    return render(request,'view_books.html', {'books': books})

def view_bissue(request):
    issue = Book_Issue.objects.order_by('-id')
    return render(request,'issue_records.html', {'issue': issue})


def edit_student_data(request,roll):
    try:
        if request.method == "POST":
            std=Students.objects.get(id=request.session['id'])    
            form = StudentsForm((request.POST),instance=std)
            if form.is_valid():
                form.save()
            del request.session['id']
            return redirect("/show_students")
        else:
            student_to_edit=Students.objects.get(roll_number=roll)
            student=StudentsForm(instance=student_to_edit)
            request.session["id"]=student_to_edit.id
            return render(request,'edit_student_data.html',{'student':student})
    except Exception as error:
        print(f"{error} occured at edit_student_data view")

def edit_book_data(request,id):
    return HttpResponse(f"<label>A book with ID: {id} could not be edited...</label><h2>The feature is comming soon</h2>")

def delete_student(request,roll):
    return HttpResponse(f"<h2>Delete Student</h2><label>Student with Roll Number: {roll} could not be deleted...</label><h2>The feature is comming soon</h2>")
    pass

def delete_book(request,id):
    return HttpResponse(f"<h2>Delete Book</h2><label>Book with ID: {id} could not be deleted..</label><h2>The feature is comming soon</h2>")

def return_issued_book(request,id):   
    obj=Book_Issue.objects.get(id=id)
    return HttpResponse(f"<h2>Return Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be returned..</label><h2>The feature is comming soon</h2>")

def edit_issued(request, id):
    obj=Book_Issue.objects.get(id=id)
    return HttpResponse(f"<h2>Edit Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be edited..</label><h2>The feature is comming soon</h2>")

Library-Management-System-main/LMS/library/templates/add_book_issue.html
<title>Add Book Issue</title>
{% extends 'base.html' %}

<body>
{% block content %}

<form method="POST" action="add_book_issue" class="form-inline">
    {% csrf_token %}
    <label>Student Details(Name)</label><br>
    <div id="student_selection">
        <div>{{form.student}}</div>
            <div><input type="text" placeholder="Quick Student Search" id="quick" onkeyup="Quick_search()">
                <div id="quick_student_search_view"></div>
            </div>
    </div>

    <br>
    <hr>
    <div class="book_selection">
        <label>Book Details(Name/UUID)</label>
        <br>
        <div><input type="text" placeholder="Quick Book Search" id="quick_book_search" onkeyup="Quick_book_search()">
            <div id="quick_book_search_view"></div>
        </div>
        <select name="book_instance" required id="id_book_instance">
            <option value="" selected>---------</option>
            {%for i in book%}
                <option class="selection" value="{{i.id}}">{{i.book.book_title}} (: {{i.id}})</option>
            {%endfor%}
        </select>
    </div>
<hr>
    <label>Remarks</label><br> <div> {{form.remarks_on_issue}}</div>
    <br> 
    <button type="submit" class="btn btn-success">Issue Book</button>

</form>


<script type="text/javascript">
    function Quick_search(){
        var input, items,view;
        input = document.getElementById('quick').value.toLowerCase();
        items = document.getElementById('id_student');
        view=document.getElementById("quick_student_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if(input !== "" && (item.toLowerCase().indexOf(input)>-1 )){
                    var list_added = document.createElement("label");
                    list_added.appendChild(document.createTextNode(item));
                    list_added.onclick =function(){
                        items.children[get_clicked_value(this.innerHTML)].setAttribute("selected",true);
                        view.style.display="none";
                        // uncomment below line to hide the search input after selection is made
                        // document.getElementById('quick').style.display="none";
                    };
                    view.appendChild(list_added);
                    view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function get_clicked_value(clicked){
        var items = document.getElementById('id_student');
        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i];
                if (item.innerHTML == clicked ) {
                    return item.getAttribute("value");
                }
        }
    }

    // Quick book search
    function Quick_book_search(){
        var input, items,view;
        input = document.getElementById('quick_book_search');
        items = document.getElementById('id_book_instance');
        view=document.getElementById("quick_book_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if((input.value.toLowerCase() !== "") && (item.toLowerCase().indexOf(input.value.toLowerCase())>-1 ) ){
                var list_added = document.createElement("label");
                list_added.appendChild(document.createTextNode(item));
                list_added.onclick =function(){
                    select_clicked_book(this.innerHTML);
                    view.style.display="none";
                    // comment below line to unhide the search input after selection is made
                    input.style.display="none"; input.value="";
                };
                view.appendChild(list_added);
                view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function select_clicked_book(clicked){
        var books = document.getElementById('id_book_instance');   
        for(i=1;i<books.children.length.valueOf();i++){
            var item=books.children[i];
                if (item.innerHTML == clicked ) {
                    item.setAttribute("selected",true);
                }
        }
    }
</script>
{% endblock %}
</body>
</html>

Library-Management-System-main/LMS/library/templates/add_new_book.html
<title>Add New Book</title>
{% extends 'base.html' %}

<body>
{% block content %}

    <div class="tablinks">
        <button onclick="opentab(name)" class="link" name="new_book">New Book</button>
        <button onclick="opentab(name)" class="link" name="new_book_instance">New Book Instance</button>
    </div>

    <div id="new_book" class="books">
        <form method="POST" action="add_new_book" class="form-inline">
            {% csrf_token %}
        <label>Book Title.</label><br><div>{{form.book_title}}</div>
        <label>Book Author.</label><br> <div> {{form.book_author}}</div>
        <label>Book Pages.</label><br> <div> {{form.book_pages}}</div>
        <label>Book summary<i>(if any)</i></label><br> <div> {{form.summary}}</div>
        <!-- <div>
            <label>Multiple Same Books</label>    
            <input type="radio" name="mode" id="multiple" value="Multiple" onclick="toggle_quantity_input(id)">
            <label>Single  book</label>    
            <input type="radio" value="single" name="mode" id="single" onclick="toggle_quantity_input(id)">

            <div id="additional_data">
                <b>Note:<i>For multiple copies, separate book number with a comma (',')</i> </b>
                <div id="multi">
                    <label>Enter the Book Quantity</label><br>
                    <input type="number" min="1" name="book_quantity"><br>
                </div>
                <label >Book Number(if any) </label><br>
                <input name="book_number_list">
            </div>
        </div> -->
        <br> <button type="submit" class="btn btn-success">Add Book</button> 
        </form>
    </div>

    <div id="new_book_instance" class="books">
    <form method="POST" action="add_new_book_instance" class="form-inline">
        {% csrf_token %}
        <label>Book</label><br><div>{{form_instance.book}}</div>
        <label>Book Number</label>
        <div>{{form_instance.book_number}}</div>
        <br> <button type="submit" class="btn btn-success">Add Book</button> 
    </form>
    </div>

<script type="text/javascript">
    function opentab(tab_name){
         var tab=document.getElementById(tab_name);
         var i, tabcontent, tablinks;
         tabcontent = document.getElementsByClassName("books");
         for (i = 0; i < tabcontent.length; i++) {
             tabcontent[i].style.display = "none";
         }
         tablinks = document.getElementsByClassName("link");
         for (i = 0; i < tablinks.length; i++) {
             tablinks[i].className = tablinks[i].className.replace(" active", "");
         }
         tab.style.display = "block";

    }
    // function toggle_quantity_input(id){
    //     var obj=document.getElementById("multi");
    //     document.getElementById("additional_data").style.display="block";
    //     if(id=="single"){
    //         obj.style.display="none";
    //     }
    //     else{
    //         obj.style.display="block";   
    //     }
    // }
</script>

{% endblock %}
</body>

</html>

Library-Management-System-main/LMS/library/templates/add_new_student.html
<title>Add New Student</title>
{% extends 'base.html' %}

<body>
    
{% block content %}
<div class="form">
<form method="POST" action="add_new_student" >
    {% csrf_token %}
    <label class="label-default">Student Details</label><br>
    <label>Roll Number:</label><br><div>{{form.roll_number}}</div>
    <label>Student Name:</label><br> <div> {{form.fullname}}</div>
    <label>Student Address:</label><br> <div> {{form.address}}</div>
    <label>Student Study Program:</label><br> <div>{{form.program}}</div><br>
    <label class="label-default">Student Guardian/Parent Details</label><br>

    <label>Full name:</label><br> <div>{{form.Guardian_name}}</div>
    <label>Valid Email:</label><br> <div>{{form.Email}}</div>
    <br> <button type="submit" class="btn btn-success">Add Student</button>
</form>
</div>
{% endblock %}

</body>
</html>

Library-Management-System-main/LMS/library/templates/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    {%load static%}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'icon/css/all.css' %}">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
    <!-- https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css -->
    <script src="{%static 'js/jquery.min.js' %}"></script>
    <!-- https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js -->
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <!-- downloaded via https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js -->
    <!-- <script src="{%static 'js/functions.js' %}"></script> -->
</head>


<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
            <label class="navbar-brand" >LIBRARY MANAGEMENT SYSTEM</label>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="add_new_student">Add Student</a></li>
                <li><a href="add_new_book">Add Book</a></li>
                <li><a href="add_book_issue">Add Issue Book</a></li>
                <li><a href="show_students">Students</a></li>
                <li><a href="view_books">Books</a></li>
                <li><a href="view_books_issued">Books Issued</a></li>

        </ul>
          
        </div>
    </nav>
 {% block content %}
    {% endblock %}

<style>
    body{

    background-image: url('static/images/bg_library.jpg');
    text-align:center;
    }

    form{
    margin-top:13em;
    }
</style>
</body>

</html>

Library-Management-System-main/LMS/library/templates/edit_student_data.html
<title>Edit Student</title>
{% extends 'base.html' %}

<body>
{% block content %}

<div class="form">
<form method="POST" action=""  id="edit_student_data">
    {% csrf_token %}
    <label>Details</label>
    <label>Roll Number:</label><br>
    {{student}}
    <!-- <input type="text" name="roll_number" value={{student.roll_number}} required><br>
    <label>Student Name:</label><br>
    <input type="text" name="student_name" value={{student.fullname}} required><br>
    <label>Student Address:</label><br> 
    <input type="text" name="address" value={{student.address}} required><br>
    <label>Student Study Program:</label><br> 
    <input type="text" name="program" value={{student.program}} required><br>
    <label>Student Guardian/Parent Details</label><br>
    <label>Full name:</label><br> 
    <input type="text" name="Guardian_name" value={{student.Guardian_name}} required><br>
    <label>Valid Email:</label><br> 
    <input type="email" name="email" value="{{student.Email}}" required><br> -->
    <br> <button type="submit" class="btn btn-success">OK</button>
</form>
</div>
{% endblock %}
</body>

</html>

Library-Management-System-main/LMS/library/templates/index.html
<title>Library Management System</title>
{% extends 'base.html' %}

<body>
{% block content %}
<h1>Library Management System</h1>
<div id="message">
    {{message}}
</div>
{%load static%}
<img src="{%static 'images/Quotes/Quote-5.png' %}">
<!-- <input type="text" value="{{choosen_img}}"> -->


<style>
    img{
        height:70%;
        width:auto;
        margin: 2%;
        border-radius:3em;
    }
</style>

{% endblock %}
</body>
</html>

Library-Management-System-main/LMS/library/templates/issue_records.html
<title> Issue Records </title>
{% extends 'base.html' %}

<body>
{% block content %}
<table class="table table-striped">
<tr>
    <th>Student name </th>
    <th>Book ID </th>
    <th>Issue Date </th>
    <th>Due Date</th>
    <th>Remarks on Issuing</th>
    <th>Remarks on Return</th>
    <th>Returned</th>
    <th>Actions</th>
</tr>
    {%for i in issue%}
    <tr>
        <td>{{i.student}}</td>
        <td>{{i.book_instance.id}}</td>
        <td>{{i.issue_date}}</td>
        <td>{{i.due_date}}</td>
        <td>{{i.remarks_on_issue}}</td>
        <td>{{i.remarks_on_return}}</td>
        <td>
            {%if i.book_instance.Is_borrowed %}
            <span><i class="fa fa-times-circle" style="color:rgb(128, 28, 0)"></i></span>
            <td>
                <a href="return_book/{{i.id}}"><i class="fa fa-arrow-alt-circle-right"></i><i class="fa fa-book"></i></a>|
                <a href="edit_issued/{{i.id}}"><i class="fa fa-edit"></i> </a>
            </td>
            {%else%}
            <span><i class="fa fa-check-circle" style="color:green"></i></span>
            <td><a href="edit_issued/{{i.id}}"><i class="fa fa-edit"></i> </a> | <a href="delete_issued/{{i.id}}"><i class="fa fa-trash-alt"></i></a></td>
            {%endif%}
        </td>

        
        
    </tr> {% endfor %}
</table>

{% endblock %}
</body>
</html>

Library-Management-System-main/LMS/library/templates/view_books.html
<title>Books</title>
{% extends 'base.html' %}

<body>
{% block content %}
<div class="search">
    <input type="text" class="form-control" id="books_search_input" name="book_name" placeholder="Search a book" onkeyup="search_books()">
    <!-- <br> -->
    <div id="book_searched">
        <label>Search Results</label>
    </div>
</div>

<table class="table table-striped">
<tr>
    <th>Book ID</th>
    <th>Book title </th>
    <th>Book author </th>
    <th>Book pages </th>
    <th>book Number </th>
    <th>Is Available</th>
    <th>Actions</th>
</tr>
    {%for book in books%}
    <tr class="book_row">
    <td >{{book.id}}</td>
    <td class="title">{{book.book.book_title}}</td>
    <td>{{book.book.book_author}}</td>
    <td>{{book.book.book_pages}}</td>
    <td >{{book.book_number}}</td>
    <td>
        {%if  book.Is_borrowed %}
        <span><i class="fa fa-times-circle" style="color:rgb(128, 28, 0)"></i></span>
        <td>
            <a href="edit/book/{{book.id}}"><i class="fa fa-edit"></i></a>
            </td>
        {%else%}
        <span><i class="fa fa-check-circle" style="color:green"></i></span>
        <td><a href="edit/book/{{book.id}}"><i class="fa fa-edit"></i></a> | <a
            href="delete/book/{{book.id}}"><i class="fa fa-trash-alt"></i></a></td>
        {%endif%}
    </td>

    </tr> {% endfor %}
</table>

<script type="text/javascript">
    function search_books(){
    var input, books,view;
    input = document.getElementById('books_search_input').value.toLowerCase();
    books = document.getElementsByClassName('book_row');
    view=document.getElementById("book_searched");
    view.replaceChildren("");

    for(i=0;i<books.length;i++){
        if(input !== ""){
            if (books[i].innerHTML.toLowerCase().indexOf(input)>-1 ) {
                var book_title = document.createTextNode(books[i].getElementsByClassName("title").item(0).textContent);
                var link=document.createElement("a");
                link.setAttribute("href","#"+books[i].getElementsByClassName("title").item(0).textContent);
                
                var list_added = document.createElement("li");
                list_added.appendChild(book_title);
                link.appendChild(list_added);
                view.appendChild(link);
                view.style.display="block";
            }
        }
        else{
            view.style.display="none";
        }
    }
}

</script>

{% endblock %}
</body>
</html>

Library-Management-System-main/LMS/library/templates/view_students.html
<title>Student</title>
{% extends 'base.html' %}

<body>
{% block content %}
<div id="message">
    {{message}}
</div>
<div class="search">
    <input type="text" class="form-control" id="student_search_input" name="student_name" placeholder="Search student" onchange="search_student()">
    <!-- <br> -->
    <div id="view_searched">
        <label>Search Results</label>
    </div>
</div>
<table class="table table-striped">
<tr>
    <th>Student Roll no </th>
    <th>Student Name </th>
    <th>Student Address </th>
    <th>Student Study Program </th>
    <th>Student Guardian/parent</th>
    <th>Guardian/parent Email</th>
    <th>Actions</th>
</tr>
    {%for student in students%}
    <tr id="{{student.fullname}}" class="student">
    <td class="roll_number">{{student.roll_number}}</td>
    <td class="name">{{student.fullname}}</td>
        <td>{{student.address}}</td>
        <td>{{student.program}}</td>
        <td>{{student.Guardian_name}}</td>
        <td>{{student.Email}}</td>
        <td><a href="edit/student/{{student.roll_number}}"><i class="fa fa-edit"></i></a> | <a
        href="delete/student/{{student.roll_number}}"><i class="fa fa-trash-alt"></i></a></td>
    </tr> {% endfor %}
</table>

<script type="text/javascript">

    function search_student(){
    var input, students,view;
    input = document.getElementById('student_search_input').value.toLowerCase();
    students = document.getElementsByClassName('student');
    view=document.getElementById("view_searched");
    view.replaceChildren("");

    for(i=0;i<students.length;i++){
        if(input !== ""){
            if (students[i].innerHTML.toLowerCase().indexOf(input)>-1 ) {
                var student_name = document.createTextNode(students[i].getElementsByClassName("name").item(0).textContent);
                var student_roll_number = document.createTextNode(students[i].getElementsByClassName("roll_number").item(0).textContent);
                var link=document.createElement("a");
                link.setAttribute("href","#"+students[i].getElementsByClassName("name").item(0).textContent);
                
                var list_added = document.createElement("li");
                list_added.appendChild(student_name);
                list_added.appendChild(student_roll_number);
                link.appendChild(list_added);
                view.appendChild(link);
                view.style.display="block";
            }
        }
        else{
            view.style.display="none";
        }
    }
}

</script>
{% endblock %}
</body>
</html>